# Streamlit Secrets Configuration
# Add these to your Streamlit Cloud App Settings > Secrets

# API Keys
OPENAI_API_KEY = "your_siliconflow_or_openai_api_key"
OPENAI_BASE_URL = "https://api.siliconflow.cn/v1"

# Stripe Configuration
STRIPE_SECRET_KEY = "sk_live_your_stripe_secret_key"  # Use sk_test_ for testing
STRIPE_PUBLISHABLE_KEY = "pk_live_your_stripe_publishable_key"
STRIPE_WEBHOOK_SECRET = "whsec_your_stripe_webhook_secret"

# Stripe Price IDs (create these in your Stripe Dashboard)
STRIPE_PREMIUM_PRICE_ID = "price_premium_monthly_id"
STRIPE_PRO_PRICE_ID = "price_pro_monthly_id"
STRIPE_SINGLE_PRICE_ID = "price_single_analysis_id"

# PayPal Configuration
PAYPAL_CLIENT_ID = "your_paypal_client_id"
PAYPAL_CLIENT_SECRET = "your_paypal_client_secret"
PAYPAL_MODE = "live"  # or "sandbox" for testing

# PayPal Plan IDs (create these in PayPal Dashboard)
PAYPAL_PREMIUM_PLAN_ID = "P-premium-plan-id"
PAYPAL_PRO_PLAN_ID = "P-pro-plan-id"

# App Configuration
APP_URL = "https://your-app-name.streamlit.app"
WEBHOOK_URL = "https://your-app-name.streamlit.app/webhook"

# Database Configuration (if using external database)
# DATABASE_URL = "postgresql://username:password@host:port/database"

# Email Configuration (for notifications)
# SENDGRID_API_KEY = "your_sendgrid_api_key"
# SUPPORT_EMAIL = "support@your-domain.com"